import { createRouter, createWebHistory } from 'vue-router';
import baseView from '@/layout/baseView.vue'
import view from '@/layout/view.vue'
import publicRoutes from './publicRoutes'

const routes = [
    {
        path: '/',
        redirect: '/dashboard'
    },
    {
      path: '/dashboard',
      name: 'dashboard',
      component: baseView,
    },
    ...publicRoutes
]

const router = createRouter({
  history: createWebHistory(import.meta.env.VITE_APP_PUBLIC_PATH),
  routes: routes,
});

const components = import.meta.glob('@/views/**/*.vue')

function _import(path) {
    return components['/src/views' + path]
}

export function getRouteList(data) {
    return (
        data
            // 菜单排序
            .sort((a, b) => a - b)
            .map((item) => {
                // 当前项
                const {
                    menuUri = '',
                    menuName = '',
                    menuType = '',
                    icon = '',
                    menuCode = '',
                    component,
                    hidden,
                    childMenuList = [],
                } = item;
                const route = {
                    meta: { name: '', icon: '', menuCode: '', menuType: 1, hidden: 0 },
                };
                // 路由地址
                route.path = menuUri;
                route.name = menuCode;
                // 导航名称
                route.meta.name = menuName;
                route.meta.icon = icon;
                route.meta.menuCode = menuCode;
                route.meta.menuType = menuType;
                // 路由组件
                const str = component.substr(0, 7);
                // 如果是自定义layout
                if (component === 'layout') {
                    route.component = view;
                } else {
                    route.component = _import(component);
                }

                // 如果是 1 将它在导航中隐藏generateRoutes
                route.meta.hidden = hidden === 1;
                // 判断是否存在子路由
                if (childMenuList && childMenuList.length) {
                    route.children = [...getRouteList(childMenuList)];
                }
                return route;
            })
    );
}

export function generateRoutes(){
    const data = [
        {
            "menuId": "9937133062572351",
            "menuName": "审计管理",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/managedAudit",
            "icon": "article",
            "priority": -1,
            "roleMenuSwitch": 0,
            "remark": "运营",
            "operatorId": "",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 1,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "9937133062572352",
                    "menuName": "审计任务",
                    "parentMenuId": "9937133062572351",
                    "menuType": 1,
                    "menuUri": "/managedAudit",
                    "icon": "",
                    "priority": -1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "",
                    "component": "/managedAudit/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937133062572351",
                        "menuName": "审计管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937133062572353",
                    "menuName": "审计任务详情-单位",
                    "parentMenuId": "9937133062572351",
                    "menuType": 1,
                    "menuUri": "/managedAudit/detail1",
                    "icon": "",
                    "priority": -1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "",
                    "component": "/managedAudit/detail_org",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937133062572351",
                        "menuName": "审计管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937133062572354",
                    "menuName": "审计任务详情-业务系统",
                    "parentMenuId": "9937133062572351",
                    "menuType": 1,
                    "menuUri": "/managedAudit/detail2",
                    "icon": "",
                    "priority": -1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "",
                    "component": "/managedAudit/detail_system",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937133062572351",
                        "menuName": "审计管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "9937100000000001",
            "menuName": "印章管理",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/manageCenter/sealManage",
            "icon": "article-create",
            "priority": 1,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 0,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "9937100000000002",
                    "menuName": "印章列表",
                    "parentMenuId": "9937100000000001",
                    "menuType": 1,
                    "menuUri": "/manageCenter/sealManage",
                    "icon": "",
                    "priority": 1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/ManageCenter/sealManage",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000001",
                        "menuName": "印章管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000003",
                    "menuName": "使用详情",
                    "parentMenuId": "9937100000000001",
                    "menuType": 1,
                    "menuUri": "/manageCenter/sealManage/detail",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/ManageCenter/components/detail",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000001",
                        "menuName": "印章管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "798242888399065088",
                    "menuName": "印章详情",
                    "parentMenuId": "9937100000000001",
                    "menuType": 1,
                    "menuUri": "/manageCenter/sealManage/detail2",
                    "icon": "",
                    "priority": 3,
                    "roleMenuSwitch": 0,
                    "remark": "运营",
                    "operatorId": "",
                    "component": "/ManageCenter/components/detail",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000001",
                        "menuName": "印章管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000004",
                    "menuName": "印章审批记录",
                    "parentMenuId": "9937100000000001",
                    "menuType": 1,
                    "menuUri": "/manageCenter/sealManage/sealApprovalRecord",
                    "icon": "",
                    "priority": 3,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "layout",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 1,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [
                        {
                            "menuId": "9937100000000005",
                            "menuName": "列表",
                            "parentMenuId": "9937100000000004",
                            "menuType": 1,
                            "menuUri": "/manageCenter/sealManage/sealApprovalRecord",
                            "icon": "",
                            "priority": 1,
                            "roleMenuSwitch": 0,
                            "remark": "运营n",
                            "operatorId": "1",
                            "component": "/sealApprovalRecord/index",
                            "showSwitch": 0,
                            "menuCode": "sealManage_sealApprovalRecord",
                            "expand": 0,
                            "redirect": "",
                            "hidden": 1,
                            "apis": null,
                            "childMenuList": [],
                            "parentMenuInfo": {
                                "menuId": "9937100000000004",
                                "menuName": "印章审批记录",
                                "parentMenuId": null,
                                "menuType": null,
                                "menuUri": null,
                                "icon": null,
                                "priority": null,
                                "roleMenuSwitch": null,
                                "remark": null,
                                "operatorId": null,
                                "component": null,
                                "showSwitch": null,
                                "menuCode": null,
                                "expand": null,
                                "redirect": null,
                                "hidden": null,
                                "apis": null,
                                "childMenuList": null,
                                "parentMenuInfo": null
                            }
                        },
                        {
                            "menuId": "9937100000000006",
                            "menuName": "详情",
                            "parentMenuId": "9937100000000004",
                            "menuType": 1,
                            "menuUri": "/manageCenter/sealManage/sealApprovalRecord/detail",
                            "icon": "",
                            "priority": 2,
                            "roleMenuSwitch": 0,
                            "remark": "运营n",
                            "operatorId": "1",
                            "component": "/sealAudit/components/detail",
                            "showSwitch": 0,
                            "menuCode": "sealApprovalRecord_detail",
                            "expand": 0,
                            "redirect": "",
                            "hidden": 1,
                            "apis": null,
                            "childMenuList": [],
                            "parentMenuInfo": {
                                "menuId": "9937100000000004",
                                "menuName": "印章审批记录",
                                "parentMenuId": null,
                                "menuType": null,
                                "menuUri": null,
                                "icon": null,
                                "priority": null,
                                "roleMenuSwitch": null,
                                "remark": null,
                                "operatorId": null,
                                "component": null,
                                "showSwitch": null,
                                "menuCode": null,
                                "expand": null,
                                "redirect": null,
                                "hidden": null,
                                "apis": null,
                                "childMenuList": null,
                                "parentMenuInfo": null
                            }
                        }
                    ],
                    "parentMenuInfo": {
                        "menuId": "9937100000000001",
                        "menuName": "印章管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "9937133062572350",
            "menuName": "任务列表",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/task",
            "icon": "article-ranking",
            "priority": 1,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "",
            "component": "layout",
            "showSwitch": 0,
            "menuCode": "",
            "expand": 1,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "795352530673602560",
                    "menuName": "列表",
                    "parentMenuId": "9937133062572350",
                    "menuType": 1,
                    "menuUri": "/task",
                    "icon": "",
                    "priority": -1,
                    "roleMenuSwitch": 0,
                    "remark": "运营",
                    "operatorId": "",
                    "component": "/task/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937133062572350",
                        "menuName": "任务列表",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937133062572349",
                    "menuName": "任务列表详情",
                    "parentMenuId": "9937133062572350",
                    "menuType": 1,
                    "menuUri": "/task/detail",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "",
                    "component": "/task/detail",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937133062572350",
                        "menuName": "任务列表",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "5150929135410981",
            "menuName": "统计中心",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/statisticalCenter",
            "icon": "change-theme",
            "priority": 2,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "/statisticalCenter/index",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 0,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [],
            "parentMenuInfo": null
        },
        {
            "menuId": "9937100000000007",
            "menuName": "用户中心",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/userCenter",
            "icon": "chart",
            "priority": 3,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 1,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "9937100000000009",
                    "menuName": "登记机关管理",
                    "parentMenuId": "9937100000000007",
                    "menuType": 1,
                    "menuUri": "/userCenter/registration",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/ManageCenter/userManage/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000007",
                        "menuName": "用户中心",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000010",
                    "menuName": "企业查询",
                    "parentMenuId": "9937100000000007",
                    "menuType": 1,
                    "menuUri": "/userCenter/corporateEnquires",
                    "icon": "",
                    "priority": 3,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/corporateEnquires/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000007",
                        "menuName": "用户中心",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "9937100000000011",
            "menuName": "应用授权",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/statisticalsCenter",
            "icon": "dashboard",
            "priority": 4,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "/ManageCenter/outSystemManage/index",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 0,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [],
            "parentMenuInfo": null
        },
        {
            "menuId": "5150929135410982",
            "menuName": "门户配置",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/potalDeploy",
            "icon": "example",
            "priority": 6,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 1,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "8992465603158316",
                    "menuName": "图片新闻管理",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy",
                    "icon": "",
                    "priority": 1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/newsManage/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158317",
                    "menuName": "新增图片新闻",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/addNews",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/newsManage/addNews",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158318",
                    "menuName": "编辑图片新闻",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/editNews",
                    "icon": "",
                    "priority": 3,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/newsManage/editNews",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158319",
                    "menuName": "图片新闻详情",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/newsDetails",
                    "icon": "",
                    "priority": 4,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/newsDetails/index",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158320",
                    "menuName": "法律解读管理",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/legalManage",
                    "icon": "",
                    "priority": 5,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/legalManage/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158321",
                    "menuName": "新增法律解读",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/addLegal",
                    "icon": "",
                    "priority": 6,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/legalManage/addLegal",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158322",
                    "menuName": "编辑法律解读",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/editLegal",
                    "icon": "",
                    "priority": 7,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/legalManage/editLegal",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "8992465603158323",
                    "menuName": "法律解读详情",
                    "parentMenuId": "5150929135410982",
                    "menuType": 1,
                    "menuUri": "/potalDeploy/legalDetails",
                    "icon": "",
                    "priority": 8,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/potalDeploy/newsDetails/index",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 1,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "5150929135410982",
                        "menuName": "门户配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "9937100000000015",
            "menuName": "系统配置",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/systemConfig",
            "icon": "exit-fullscreen",
            "priority": 7,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 0,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "9937100000000016",
                    "menuName": "系统参数配置",
                    "parentMenuId": "9937100000000015",
                    "menuType": 1,
                    "menuUri": "/systemConfig",
                    "icon": "",
                    "priority": 1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/systemConfig/system/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000015",
                        "menuName": "系统配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000017",
                    "menuName": "证书配置",
                    "parentMenuId": "9937100000000015",
                    "menuType": 1,
                    "menuUri": "/systemConfig/cert",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/systemConfig/cert/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000015",
                        "menuName": "系统配置",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "9937100000000018",
            "menuName": "日志管理",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/logMange",
            "icon": "eye",
            "priority": 8,
            "roleMenuSwitch": 0,
            "remark": "运营n",
            "operatorId": "1",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 0,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "9937100000000019",
                    "menuName": "操作日志",
                    "parentMenuId": "9937100000000018",
                    "menuType": 1,
                    "menuUri": "/logMange",
                    "icon": "",
                    "priority": 1,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/logs/operateLog",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000018",
                        "menuName": "日志管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000020",
                    "menuName": "授权日志",
                    "parentMenuId": "9937100000000018",
                    "menuType": 1,
                    "menuUri": "/logMange/authorizationLog",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/authorizationLog/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000018",
                        "menuName": "日志管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000021",
                    "menuName": "企业变更日志",
                    "parentMenuId": "9937100000000018",
                    "menuType": 1,
                    "menuUri": "/logMange/companyLogs",
                    "icon": "",
                    "priority": 3,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/ManageCenter/companyLogs/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000018",
                        "menuName": "日志管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "9937100000000099",
                    "menuName": "应用日志",
                    "parentMenuId": "9937100000000018",
                    "menuType": 1,
                    "menuUri": "/logMange/applyLog",
                    "icon": "",
                    "priority": 4,
                    "roleMenuSwitch": 0,
                    "remark": "运营n",
                    "operatorId": "1",
                    "component": "/logs/applyLog",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "9937100000000018",
                        "menuName": "日志管理",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        },
        {
            "menuId": "794965488869445632",
            "menuName": "系统账号",
            "parentMenuId": "",
            "menuType": 1,
            "menuUri": "/user",
            "icon": "eye-open",
            "priority": 12,
            "roleMenuSwitch": 0,
            "remark": "运营",
            "operatorId": "",
            "component": "layout",
            "showSwitch": 1,
            "menuCode": "",
            "expand": 1,
            "redirect": "",
            "hidden": 0,
            "apis": null,
            "childMenuList": [
                {
                    "menuId": "794979438830948352",
                    "menuName": "用户管理",
                    "parentMenuId": "794965488869445632",
                    "menuType": 1,
                    "menuUri": "/user",
                    "icon": "",
                    "priority": 0,
                    "roleMenuSwitch": 0,
                    "remark": "运营",
                    "operatorId": "",
                    "component": "/MenuMange/user/index",
                    "showSwitch": 1,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "794965488869445632",
                        "menuName": "系统账号",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "792761083038404608",
                    "menuName": "角色管理",
                    "parentMenuId": "794965488869445632",
                    "menuType": 1,
                    "menuUri": "/user/role",
                    "icon": "",
                    "priority": 1,
                    "roleMenuSwitch": 0,
                    "remark": "运营",
                    "operatorId": "",
                    "component": "/MenuMange/role/index",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "794965488869445632",
                        "menuName": "系统账号",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "792761230669516800",
                    "menuName": "菜单管理",
                    "parentMenuId": "794965488869445632",
                    "menuType": 1,
                    "menuUri": "/user/menu",
                    "icon": "",
                    "priority": 2,
                    "roleMenuSwitch": 0,
                    "remark": "运营",
                    "operatorId": "",
                    "component": "/MenuMange/menu/index",
                    "showSwitch": 0,
                    "menuCode": "",
                    "expand": 0,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [],
                    "parentMenuInfo": {
                        "menuId": "794965488869445632",
                        "menuName": "系统账号",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                },
                {
                    "menuId": "795690471769903104",
                    "menuName": "机构管理",
                    "parentMenuId": "794965488869445632",
                    "menuType": 1,
                    "menuUri": "/user/organization",
                    "icon": "",
                    "priority": 4,
                    "roleMenuSwitch": 0,
                    "remark": "运营",
                    "operatorId": "",
                    "component": "layout",
                    "showSwitch": 1,
                    "menuCode": "systemUserOrganization",
                    "expand": 1,
                    "redirect": "",
                    "hidden": 0,
                    "apis": null,
                    "childMenuList": [
                        {
                            "menuId": "795723251589451776",
                            "menuName": "机构管理",
                            "parentMenuId": "795690471769903104",
                            "menuType": 1,
                            "menuUri": "/user/organization",
                            "icon": "",
                            "priority": 1,
                            "roleMenuSwitch": 0,
                            "remark": "运营",
                            "operatorId": "",
                            "component": "/wujie/user",
                            "showSwitch": 1,
                            "menuCode": "systemUserOrganizationHidden",
                            "expand": 0,
                            "redirect": "",
                            "hidden": 1,
                            "apis": null,
                            "childMenuList": [],
                            "parentMenuInfo": {
                                "menuId": "795690471769903104",
                                "menuName": "机构管理",
                                "parentMenuId": null,
                                "menuType": null,
                                "menuUri": null,
                                "icon": null,
                                "priority": null,
                                "roleMenuSwitch": null,
                                "remark": null,
                                "operatorId": null,
                                "component": null,
                                "showSwitch": null,
                                "menuCode": null,
                                "expand": null,
                                "redirect": null,
                                "hidden": null,
                                "apis": null,
                                "childMenuList": null,
                                "parentMenuInfo": null
                            }
                        },
                        {
                            "menuId": "795720121833361408",
                            "menuName": "机构编辑",
                            "parentMenuId": "795690471769903104",
                            "menuType": 1,
                            "menuUri": "/user/organization/edit",
                            "icon": "",
                            "priority": 2,
                            "roleMenuSwitch": 0,
                            "remark": "运营",
                            "operatorId": "",
                            "component": "/wujie/user",
                            "showSwitch": 1,
                            "menuCode": "systemUserOrganizationEdit",
                            "expand": 0,
                            "redirect": "",
                            "hidden": 1,
                            "apis": null,
                            "childMenuList": [],
                            "parentMenuInfo": {
                                "menuId": "795690471769903104",
                                "menuName": "机构管理",
                                "parentMenuId": null,
                                "menuType": null,
                                "menuUri": null,
                                "icon": null,
                                "priority": null,
                                "roleMenuSwitch": null,
                                "remark": null,
                                "operatorId": null,
                                "component": null,
                                "showSwitch": null,
                                "menuCode": null,
                                "expand": null,
                                "redirect": null,
                                "hidden": null,
                                "apis": null,
                                "childMenuList": null,
                                "parentMenuInfo": null
                            }
                        }
                    ],
                    "parentMenuInfo": {
                        "menuId": "794965488869445632",
                        "menuName": "系统账号",
                        "parentMenuId": null,
                        "menuType": null,
                        "menuUri": null,
                        "icon": null,
                        "priority": null,
                        "roleMenuSwitch": null,
                        "remark": null,
                        "operatorId": null,
                        "component": null,
                        "showSwitch": null,
                        "menuCode": null,
                        "expand": null,
                        "redirect": null,
                        "hidden": null,
                        "apis": null,
                        "childMenuList": null,
                        "parentMenuInfo": null
                    }
                }
            ],
            "parentMenuInfo": null
        }
    ]
    return getRouteList(data)
}

export default router;
